using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Threading;
using System.Threading.Tasks;
using RtspClientSharp.Codecs.Video;
using RtspClientSharp.MediaParsers;
using RtspClientSharp.RawFrames;
using RtspClientSharp.RawFrames.Video;
using RtspClientSharp.Rtp;
using RtspClientSharp.Rtsp;
using RtspClientSharp.Ts;
using RtspClientSharp.Utils;

namespace RtspClientSharp.RtpClient
{
    public sealed class RtpClient : IRtpClient
    {
        private const int UdpSocketReceiveBufferSize = 512 * 1024;
        private UdpClient _rtpClient;
        private int _disposed;
        private long _receivedDatagramCount;
        private long _generatedFrameCount;
        private long _dispatcherDroppedFrameCount;
        private readonly byte[] _receiveBuffer =
            new byte[Constants.UdpReceiveBufferSize + RawVideoFramePadding.Size];
        public ConnectionParameters ConnectionParameters { get; }
        public int Timeout { get; set; } = 3000;

        /// <summary>
        /// Delivers each generated frame on the receive/parser call stack instead
        /// of copying it to the bounded display dispatcher. Enable this only when
        /// subscribers consume the frame synchronously before returning. The
        /// WinForms control enables it for its private transport client.
        /// </summary>
        public bool UseInlineFrameDelivery { get; set; }

        public event Action<RawFrame> RawFrameReceived;
        public event EventHandler<RawFrame> RawFrameGenerated;
        public event EventHandler<RawFrame> FrameReceived;

        /// <summary>
        /// Selects the direct-RTP video codec. Auto is the default and probes the
        /// RTP payload structure for H.264, H.265, or RFC 2435 MJPEG.
        /// Raw MPEG-TS selects its video codec from the PMT.
        /// </summary>
        public CodecInfoType VideoCodec { get; set; } = CodecInfoType.Auto;

        /// <summary>
        /// Backward-compatible H.264/MJPEG selector. New code should use
        /// <see cref="VideoCodec"/> and leave it at Auto when the source is unknown.
        /// </summary>
        [Obsolete("Use VideoCodec. The default now auto-detects the codec.")]
        public bool IsH264
        {
            get => VideoCodec != CodecInfoType.MJPEG;
            set => VideoCodec = value ? CodecInfoType.H264 : CodecInfoType.MJPEG;
        }
        /// <summary>
        /// The media packet format selected for the current direct UDP session.
        /// This is <see cref="MediaTransportMode.Auto"/> until the first datagram
        /// is classified.
        /// </summary>
        public MediaTransportMode DetectedTransportMode
        {
            get
            {
                ITransportStream currentStream = stream;
                if (currentStream is AutoDetectingTransportStream autoStream)
                    return autoStream.DetectedMode;

                return (MediaTransportMode)Volatile.Read(ref _detectedTransportMode);
            }
        }

        /// <summary>
        /// The video codec selected for the current direct-media session. This is
        /// Auto until RTP probing or the MPEG-TS PMT identifies the codec.
        /// </summary>
        public CodecInfoType DetectedVideoCodec
        {
            get
            {
                ITransportStream currentStream = stream;
                if (currentStream is IVideoCodecDetector codecDetector &&
                    codecDetector.DetectedVideoCodec != CodecInfoType.Auto)
                    return codecDetector.DetectedVideoCodec;

                return (CodecInfoType)Volatile.Read(ref _detectedVideoCodec);
            }
        }
        /// <summary>
        /// Optional Annex-B SPS/PPS bytes for a direct RTP H.264 stream. Direct RTP has no
        /// SDP exchange, so this must be supplied when the sender does not repeat them in-band.
        /// </summary>
        public byte[] H264SpsPpsBytes { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// Optional Annex-B VPS/SPS/PPS bytes for direct RTP H.265. Most sources
        /// repeat these parameter sets in-band, in which case this stays empty.
        /// </summary>
        public byte[] H265VpsSpsPpsBytes { get; set; } = Array.Empty<byte>();
        /// <summary>Number of non-empty UDP datagrams read by this client.</summary>
        public long ReceivedDatagramCount => Interlocked.Read(ref _receivedDatagramCount);
        /// <summary>Number of complete media frames generated by the parser.</summary>
        public long GeneratedFrameCount => Interlocked.Read(ref _generatedFrameCount);
        /// <summary>Number of parsed frames rejected by the bounded dispatcher.</summary>
        public long DispatcherDroppedFrameCount => Interlocked.Read(ref _dispatcherDroppedFrameCount);

        private ITransportStream stream;
        private RawFrameDispatcher _frameDispatcher;
        private int _detectedTransportMode = (int)MediaTransportMode.Auto;
        private int _detectedVideoCodec = (int)CodecInfoType.Auto;

        public RtpClient(ConnectionParameters connectionParameters)
        {
            ConnectionParameters = connectionParameters ??
                                   throw new ArgumentNullException(nameof(connectionParameters));

        }

        ~RtpClient()
        {
            Dispose();
        }

        /// <summary>
        /// Connect to endpoint and start RTSP session
        /// </summary>
        /// <exception cref="OperationCanceledException"></exception>
        /// <exception cref="InvalidCredentialException"></exception>
        /// <exception cref="RtspClientException"></exception>
        public async Task ConnectAsync(CancellationToken token)
        {
            await Task.Run(async () =>
            {
                _rtpClient = CreateRtpClientInternal(ConnectionParameters.ConnectionUri.Host, ConnectionParameters.ConnectionUri.Port);

                try
                {
                    Task connectionTask = SetupConnection();

                    if (connectionTask.IsCompleted)
                    {
                        await connectionTask;
                        return;
                    }

                    var delayTaskCancelTokenSource = new CancellationTokenSource();
                    using (var linkedTokenSource =
                        CancellationTokenSource.CreateLinkedTokenSource(delayTaskCancelTokenSource.Token, token))
                    {
                        CancellationToken delayTaskToken = linkedTokenSource.Token;

                        Task delayTask = Task.Delay(Timeout, delayTaskToken);

                        if (connectionTask != await Task.WhenAny(connectionTask, delayTask))
                        {
                            connectionTask.IgnoreExceptions();

                            if (delayTask.IsCanceled)
                                throw new OperationCanceledException();

                            throw new TimeoutException();
                        }

                        delayTaskCancelTokenSource.Cancel();
                        await connectionTask;
                    }
                }
                catch (Exception e)
                {
                    _rtpClient.Dispose();
                    Volatile.Write(ref _rtpClient, null);

                    if (e is TimeoutException)
                        throw new RtspClientException("Connection timeout", e);

                    if (e is OperationCanceledException)
                        throw;

                    if (!(e is RtspClientException))
                        throw new RtspClientException("Connection error", e);

                    throw;
                }
            }, token).ConfigureAwait(false);
        }

        private Task SetupConnection()
        {
            IMediaPayloadParser mediaPayloadParser =
                ConnectionParameters.TransportMode == MediaTransportMode.MpegTs
                    ? null
                    : CreateRtpVideoPayloadParser();

            IRtpSequenceAssembler rtpSequenceAssembler = mediaPayloadParser == null
                ? null
                : new RtpSequenceAssembler(Constants.UdpReceiveBufferSize, 256, true);
            if (mediaPayloadParser != null)
                mediaPayloadParser.FrameGenerated = OnFrameGeneratedThreadSafe;

            Func<ITransportStream> rtpStreamFactory = () =>
                new RtpStream(mediaPayloadParser, 90000, rtpSequenceAssembler, true);
            Func<ITransportStream> mpegTsStreamFactory = () => new TsStream(OnFrameGeneratedThreadSafe);

            Volatile.Write(ref _detectedVideoCodec,
                (int)(VideoCodec == CodecInfoType.Auto ? CodecInfoType.Auto : VideoCodec));

            switch (ConnectionParameters.TransportMode)
            {
                case MediaTransportMode.Rtp:
                    stream = rtpStreamFactory();
                    Volatile.Write(ref _detectedTransportMode, (int)MediaTransportMode.Rtp);
                    break;
                case MediaTransportMode.MpegTs:
                    stream = mpegTsStreamFactory();
                    Volatile.Write(ref _detectedTransportMode, (int)MediaTransportMode.MpegTs);
                    break;
                case MediaTransportMode.Auto:
                    stream = new AutoDetectingTransportStream(MediaTransportMode.Auto,
                        rtpStreamFactory, mpegTsStreamFactory);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(ConnectionParameters.TransportMode));
            }

            return Task.CompletedTask;
        }

        private IMediaPayloadParser CreateRtpVideoPayloadParser()
        {
            switch (VideoCodec)
            {
                case CodecInfoType.Auto:
                    return new AutoDetectingVideoPayloadParser(H264SpsPpsBytes, H265VpsSpsPpsBytes);
                case CodecInfoType.H264:
                    return MediaPayloadParser.CreateFrom(new H264CodecInfo
                    {
                        SpsPpsBytes = H264SpsPpsBytes ?? Array.Empty<byte>()
                    });
                case CodecInfoType.H265:
                    return MediaPayloadParser.CreateFrom(new H265CodecInfo
                    {
                        VpsBytes = H265VpsSpsPpsBytes ?? Array.Empty<byte>()
                    });
                case CodecInfoType.MJPEG:
                    return MediaPayloadParser.CreateFrom(new MJPEGCodecInfo());
                default:
                    throw new ArgumentOutOfRangeException(nameof(VideoCodec));
            }
        }

        private async Task ReceiveRtpFromUdpAsync()
        {
            int bytesRead = await _rtpClient.Client.ReceiveAsync(
                new ArraySegment<byte>(_receiveBuffer), SocketFlags.None).ConfigureAwait(false);

            ProcessReceivedDatagram(bytesRead);
        }

        private void ProcessReceivedDatagram(int bytesRead)
        {
            if (bytesRead == 0)
                return;

            Interlocked.Increment(ref _receivedDatagramCount);
            stream.Process(new ArraySegment<byte>(_receiveBuffer, 0, bytesRead));
        }

        /// <summary>
        /// Receives direct UDP media until cancelled or the endpoint is idle for
        /// <see cref="Timeout"/> milliseconds. Unlike the legacy one-read API, this
        /// keeps one blocking receive loop and one watchdog alive for the whole
        /// session instead of allocating an async socket task for every datagram.
        /// </summary>
        public Task ReceiveLoopAsync(CancellationToken token)
        {
            if (_rtpClient == null)
                throw new InvalidOperationException("Client should be connected first");

            return Task.Factory.StartNew(() => ReceiveLoopBlocking(token), CancellationToken.None,
                TaskCreationOptions.LongRunning, TaskScheduler.Default);
        }

        private void ReceiveLoopBlocking(CancellationToken token)
        {
            if (_rtpClient == null)
                throw new InvalidOperationException("Client should be connected first");

            Socket socket = _rtpClient.Client;
            socket.ReceiveTimeout = Math.Max(1, Timeout);

            using (token.Register(() =>
            {
                try
                {
                    socket.Close();
                }
                catch
                {
                    // Closing the socket is only used to wake Socket.Receive.
                }
            }))
            {
                try
                {
                    while (!token.IsCancellationRequested)
                    {
                        int bytesRead = socket.Receive(_receiveBuffer, 0, _receiveBuffer.Length,
                            SocketFlags.None);

                        ProcessReceivedDatagram(bytesRead);
                    }
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception exception)
                {
                    if (token.IsCancellationRequested)
                        throw new OperationCanceledException(token);

                    if (exception is SocketException socketException &&
                        socketException.SocketErrorCode == SocketError.TimedOut)
                    {
                        throw new RtspClientException("Receive timeout", new TimeoutException());
                    }

                    throw new RtspClientException("Receive error", exception);
                }
            }
        }

        /// <summary>
        /// Receive frames. 
        /// Should be called after successful connection to endpoint or InvalidOperationException will be thrown
        /// </summary>
        /// <exception cref="OperationCanceledException"></exception>
        /// <exception cref="RtspClientException"></exception>
        /// <exception cref="InvalidOperationException"></exception>
        public async Task ReceiveAsync(CancellationToken token)
        {
            if (_rtpClient == null)
                throw new InvalidOperationException("Client should be connected first");

            try
            {
                Task receiveInternalTask = ReceiveRtpFromUdpAsync();

                if (receiveInternalTask.IsCompleted)
                {
                    await receiveInternalTask;
                    return;
                }

                // ReceiveRtpFromUdpAsync reads exactly one datagram. The old loop
                // recreated two cancellation sources and a linked timeout task for
                // every packet, even though no second receive could complete while
                // this task was pending. One timeout task is sufficient and keeps
                // the hot receive path allocation-light.
                using (var timeoutCancellation = CancellationTokenSource.CreateLinkedTokenSource(token))
                {
                    Task timeoutTask = Task.Delay(Timeout, timeoutCancellation.Token);
                    Task result = await Task.WhenAny(receiveInternalTask, timeoutTask).ConfigureAwait(false);

                    if (result == receiveInternalTask)
                    {
                        timeoutCancellation.Cancel();
                        await receiveInternalTask;
                        return;
                    }

                    if (timeoutTask.IsCanceled)
                    {
                        _rtpClient.Dispose();
                        await Task.WhenAny(receiveInternalTask);
                        throw new OperationCanceledException(token);
                    }

                    receiveInternalTask.IgnoreExceptions();
                    throw new RtspClientException("Receive timeout", new TimeoutException());
                }
            }
            catch (InvalidOperationException)
            {
                throw;
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception e)
            {
                throw new RtspClientException("Receive error", e);
            }
            //finally
            //{
            //    _rtpClient.Dispose();
            //    Volatile.Write(ref _rtpClient, null);
            //}
        }

        /// <summary>
        /// Clean up unmanaged resources
        /// </summary>
        public void Dispose()
        {
            if (Interlocked.CompareExchange(ref _disposed, 1, 0) != 0)
                return;

            Interlocked.Exchange(ref _frameDispatcher, null)?.Dispose();
            _rtpClient?.Dispose();

            GC.SuppressFinalize(this);
        }

        private UdpClient CreateRtpClientInternal(string ip, int port)
        {
            var client = new UdpClient();
            // A single encoded video frame can arrive as a burst of RTP datagrams. Keep
            // enough kernel-side queue space to absorb that burst while the parser and
            // frame dispatcher process the previous datagram.
            client.Client.ReceiveBufferSize = UdpSocketReceiveBufferSize;
            if (ip != null)
            {
                IPAddress address = IPAddress.Parse(ip);

                try
                {
                    client.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseUnicastPort, true);
                }
                catch
                {
                    client.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
                }

                client.Client.Bind(new IPEndPoint(IPAddress.Any, port));

                if (IsMulticast(address))
                {
                    JoinMulticastGroup(client, address);
                }

                //if(address.Address == IPAddress.Broadcast.Address)
                //{
                //    client.EnableBroadcast = true;
                //}
            }

            return client;
        }

        private void JoinMulticastGroup(UdpClient client, IPAddress multicastAddress)
        {
            IPAddress multicastInterfaceAddress = ConnectionParameters.MulticastInterfaceAddress;
            if (multicastInterfaceAddress != null)
            {
                client.JoinMulticastGroup(multicastAddress, multicastInterfaceAddress);
                return;
            }

            if (multicastAddress.AddressFamily == AddressFamily.InterNetworkV6)
            {
                foreach (int i in GetMulticastCapableInterfaceIndex())
                    client.JoinMulticastGroup(i, multicastAddress);

                return;
            }

            IPAddress[] interfaces = GetMulticastCapableInterface();
            if (interfaces.Length == 0)
            {
                client.JoinMulticastGroup(multicastAddress);
                return;
            }

            Exception lastException = null;
            bool joined = false;

            foreach (IPAddress localAddress in interfaces)
            {
                try
                {
                    client.JoinMulticastGroup(multicastAddress, localAddress);
                    joined = true;
                }
                catch (Exception e) when (e is SocketException || e is ArgumentException)
                {
                    lastException = e;
                }
            }

            if (!joined && lastException != null)
                throw lastException;
        }


        private void OnFrameGeneratedThreadSafe(RawFrame frame)
        {
            Interlocked.Increment(ref _generatedFrameCount);
            // RawFrame segments point into parser storage that is reused for the next
            // frame. The normal path copies before dispatch; the inline path invokes the
            // consumer before the parser can reuse that storage.
            if (RawFrameGenerated != null)
                RaiseRawFrameGenerated(frame);

            if (UseInlineFrameDelivery)
            {
                try
                {
                    DispatchFrameToSubscribers(frame);
                }
                catch (Exception exception)
                {
                    // Keep inline consumers from terminating the receive/parser path,
                    // matching the protection used by RawFrameDispatcher.
                    Debug.WriteLine(exception);
                }

                return;
            }

            if (RawFrameReceived == null && FrameReceived == null)
                return;

            RawFrameDispatcher frameDispatcher = GetFrameDispatcher();
            if (frameDispatcher == null || !frameDispatcher.TryEnqueue(frame))
                Interlocked.Increment(ref _dispatcherDroppedFrameCount);
        }

        private RawFrameDispatcher GetFrameDispatcher()
        {
            if (Volatile.Read(ref _disposed) != 0)
                return null;

            RawFrameDispatcher frameDispatcher = Volatile.Read(ref _frameDispatcher);
            if (frameDispatcher != null)
                return frameDispatcher;

            var newFrameDispatcher = new RawFrameDispatcher(DispatchFrameToSubscribers);
            if (Volatile.Read(ref _disposed) != 0)
            {
                newFrameDispatcher.Dispose();
                return null;
            }

            frameDispatcher = Interlocked.CompareExchange(ref _frameDispatcher, newFrameDispatcher, null);
            if (frameDispatcher != null)
                newFrameDispatcher.Dispose();

            return frameDispatcher ?? newFrameDispatcher;
        }

        private void DispatchFrameToSubscribers(RawFrame frame)
        {
            RawFrameReceived?.Invoke(frame);
            FrameReceived?.Invoke(this, frame);
        }

        private void RaiseRawFrameGenerated(RawFrame frame)
        {
            try
            {
                RawFrameGenerated?.Invoke(this, frame);
            }
            catch (Exception exception)
            {
                // A tap such as recording must not be able to terminate the
                // receive/parser path. The subscriber owns its error reporting.
                System.Diagnostics.Debug.WriteLine(exception);
            }
        }

        static bool IsMulticast(IPAddress ip)
        {
            if(ip.AddressFamily == AddressFamily.InterNetwork)
            {
                byte firstOctet = ip.GetAddressBytes()[0];
                return firstOctet >= 224 && firstOctet <= 239;
            }
            else if (ip.AddressFamily == AddressFamily.InterNetworkV6)
            {
                return ip.IsIPv6Multicast;
            }

            return false;
        }

        private static IPAddress[] GetMulticastCapableInterface()
        {
            List<IPAddress> list = new List<IPAddress>();
            foreach (NetworkInterface ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                if (ni.OperationalStatus != OperationalStatus.Up) continue;

                if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback ||
                   ni.NetworkInterfaceType == NetworkInterfaceType.Tunnel) continue;

                if (!ni.SupportsMulticast) continue;

                if (ni.Description.ToLower().Contains("virtual") || ni.Name.ToLower().Contains("vmware")) continue;

                var ipProps = ni.GetIPProperties();
                foreach (var ip in ipProps.UnicastAddresses)
                {
                    if (ip.Address.AddressFamily == AddressFamily.InterNetwork && !IPAddress.IsLoopback(ip.Address))
                    {
                        list.Add(ip.Address);
                    }
                }
            }

            return list.ToArray();
        }

        private static int[] GetMulticastCapableInterfaceIndex()
        {
            List<int> list = new List<int>();
            foreach (NetworkInterface ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                if (ni.OperationalStatus != OperationalStatus.Up) continue;

                if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback ||
                   ni.NetworkInterfaceType == NetworkInterfaceType.Tunnel) continue;

                if (!ni.SupportsMulticast) continue;

                string desc = ni.Description.ToLower();
                string name = ni.Name.ToLower();
                if (desc.Contains("virtual") ||
                   name.Contains("vmware")) continue;

                var ipProps = ni.GetIPProperties();
                IPv4InterfaceProperties ipv4Props = ipProps.GetIPv4Properties();
                if (ipv4Props == null) continue;

                foreach (var ip in ipProps.UnicastAddresses)
                {
                    if (ip.Address.AddressFamily != AddressFamily.InterNetwork) continue;
                    if (IPAddress.IsLoopback(ip.Address)) continue;

                    list.Add(ipv4Props.Index);
                    break;
                }
            }

            return list.ToArray();
        }
    }
}
